---
title: "T1-DISCO safety data"
author: "Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    number_sections: yes
    theme: readable
    toc: yes
    toc_depth: 2
    toc_float: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,warning = FALSE, message = FALSE)

library(knitr)
library(dplyr)
library(readxl)
library(ggplot2)
library(tidyr)

# specify user for paths
user <- Sys.info()[["user"]]
if (user == "laurapyle") {
  data_path <- "/Users/laurapyle/Library/CloudStorage/OneDrive-UW/Bjornstad/Biostatistics Core Shared Drive/T1-DISCO/Data raw"
  rand_path <- "/Users/laurapyle/Library/CloudStorage/OneDrive-UW/T1-DISCO randomization"
} else if (user == "lpyle") {
  data_path <- "/Users/lpyle/Library/CloudStorage/OneDrive-UW/Bjornstad/Biostatistics Core Shared Drive/T1-DISCO/Data raw"
  rand_path <- "/Users/lpyle/Library/CloudStorage/OneDrive-UW/T1-DISCO randomization"
} else if (user == "pylell") {
  data_path <- "/Users/pylell/Library/CloudStorage/OneDrive-UW/Bjornstad/Biostatistics Core Shared Drive/T1-DISCO/Data raw"
  rand_path <- "/Users/pylell/Library/CloudStorage/OneDrive-UW/T1-DISCO randomization"
} else {
  stop("Unknown user: please specify root path for this user.")
}

```

The plots below are spaghetti plots or profile plots of raw data. Black triangles represent the mean at each time point.

```{r echo=FALSE, warning= FALSE, comment="", include=FALSE}
# Vectorized function for multiple IDs
extract_numeric_id <- function(ids) {
  # Use sapply to apply to each element
  sapply(strsplit(ids, "-"), function(x) as.numeric(x[length(x)]))
}

# read in randomizations
filename <- "T1DISCO randomization.xlsx"
full_path <- file.path(rand_path, filename)
rand <- read_xlsx(full_path, sheet = "Sheet1")
rand_check <- read_xlsx(full_path, sheet = "Sheet2")
# double data entry check
rand == rand_check
# fix IDs
rand$`Record ID` <- extract_numeric_id(rand$ID)

# read in lab data
filename <- "T1DISCO-SafetyLabs_DATA_LABELS_2025-10-02_1804.xlsx"
full_path <- file.path(data_path, filename)
labs <- read_xlsx(full_path, na = c("-", "", " ", "-9999", "-1"))
labs$`Visit Type` <- factor(labs$`Visit Type`, levels = c("Screen", "Baseline", "Month 1", "Month 2", "Month 4", "Month 6", "Post-Tx", "Month 9"))
# fix IDs
labs$`Record ID` <- extract_numeric_id(labs$`Record ID`)
# need to collapse Screening and Baseline - either take average, or fill down and just show baseline?
sb <- labs %>% filter(`Visit Type` %in% c("Screen", "Baseline"))
labs <- labs %>% filter(!`Visit Type` %in% c("Screen", "Baseline"))
sb <- sb %>% group_by(`Record ID`) %>% fill(c(`A1c (%)`,`Sodium (mmol/L)`,`Potassium (mmol/L)`,`Chloride (mmol/L)`,`Bicarb (mmol/L)`,`Glucose (mg/dl)`,`BUN (mg/dl)`,
                                             `Serum creatinine (mg/dl)`, `Calcium (mg/dl)`,`Total Bilirubin (mg/dl)`,`Alk Phos (U/L)`,`ALT (U/L)`,`AST (U/L)`,
                                             `Total Protein, S (g/dl)`,`Albumin (g/dl)`,`eGFR`,`BMI`), .direction = "down") 
labs <- rbind(labs, sb)
labs$`Record ID` <- as.numeric(labs$`Record ID`)
labs <- labs %>% filter(!`Visit Type` == "Screen")
# fix a bmi value
labs$BMI <- ifelse(labs$`Record ID` == 23 & labs$`Visit Type` == "Month 1", 34.3, labs$BMI)
labs <- full_join(labs, rand, by = "Record ID")
labs <- labs %>% filter(!is.na(labs$`Visit Type`))
labs$`Visit Type` <- droplevels(labs$`Visit Type`)

# read in CGM data
filename <- "T1DISCO-CGM_DATA_LABELS_2025-10-02_1809.xlsx"
full_path <- file.path(data_path, filename)
cgm <- read_xlsx(full_path, na = c("-", "", " ", "-9999"))
cgm <- cgm %>% filter(!is.na(Week))
# fix IDs
cgm$`Record ID` <- extract_numeric_id(cgm$`Record ID`)
cgm$`Record ID` <- as.numeric(cgm$`Record ID`)
# create new variable combining week and dose
cgm <- cgm %>% mutate(
  week_dose = case_when(
  Week == "Run-In 1" ~ "Run-In 1",
  Week == "Run-In 2" ~ "Run-In 2",
  Week %in% c("Dose 1 Week 1", "Dose 1 Week 2", "Dose 1 Week 3", "Dose 1 Week 4") ~ "Dose 1",
  Week %in% c("Dose 2 Week 1", "Dose 2 Week 2", "Dose 2 Week 3", "Dose 2 Week 4") ~ "Dose 2",
  Week %in% c("Dose 3 Month 2", "Dose 3 Month 3", "Dose 3 Month 4", "Dose 3 Month 5",
              "Dose 3 Week 1", "Dose 3 Week 2", "Dose 3 Week 3", "Dose 3 Week 4") ~ "Dose 3",
  Week == "Dose 3 Week 31" ~ "Dose 3 Week 31",
  .default = NA
  ))
# order factor
cgm$week_dose <- factor(cgm$week_dose, levels = c("Run-In 1", "Run-In 2", "Dose 1", "Dose 2", "Dose 3", "Dose 3 Week 31"))
# take the average across week_dose
cgm_summary <- cgm %>% group_by(`Record ID`, week_dose) %>% summarise(TBRmean = mean(`Time Below Range (TBR < 70 mg/dL)`, na.rm = T), 
                                                              SHmean = mean(`Severe Hypoglycemia (< 54 mg/dL)`, na.rm = T))
cgm_summary <- full_join(cgm_summary, rand, by = "Record ID")
# delete run-in visits from people who weren't randomized
cgm_summary <- cgm_summary %>% filter(!is.na(Group))
cgm_summary <- cgm_summary %>% filter(!is.na(week_dose))

# plots of labs
p_a1c <- ggplot(data = labs, aes(x = `Visit Type`, y = `A1c (%)`, group = `Record ID`, color = as.factor(`Record ID`))) + 
  geom_line(show.legend = F) + guides(fill = "none") + stat_summary(aes(group = 1), geom = "point", fun.y = mean,
    shape = 17, size = 3, show.legend = F) + facet_wrap(~ Group)
p_sod <- ggplot(data = labs, aes(x = `Visit Type`, y = `Sodium (mmol/L)`, group = `Record ID`, color = as.factor(`Record ID`))) + 
  geom_line(show.legend = F) + guides(fill = "none") + stat_summary(aes(group = 1), geom = "point", fun.y = mean,
    shape = 17, size = 3, show.legend = F) + facet_wrap(~ Group)
p_pot <- ggplot(data = labs, aes(x = `Visit Type`, y = `Potassium (mmol/L)`, group = `Record ID`, color = as.factor(`Record ID`))) + 
  geom_line(show.legend = F) + guides(fill = "none") + stat_summary(aes(group = 1), geom = "point", fun.y = mean,
    shape = 17, size = 3, show.legend = F) + facet_wrap(~ Group)
p_chlor <- ggplot(data = labs, aes(x = `Visit Type`, y = `Chloride (mmol/L)`, group = `Record ID`, color = as.factor(`Record ID`))) + 
  geom_line(show.legend = F) + guides(fill = "none") + stat_summary(aes(group = 1), geom = "point", fun.y = mean,
    shape = 17, size = 3, show.legend = F) + facet_wrap(~ Group)
p_bicarb <- ggplot(data = labs, aes(x = `Visit Type`, y = `Bicarb (mmol/L)`, group = `Record ID`, color = as.factor(`Record ID`))) + 
  geom_line(show.legend = F) + guides(fill = "none") + stat_summary(aes(group = 1), geom = "point", fun.y = mean,
    shape = 17, size = 3, show.legend = F) + facet_wrap(~ Group)
p_gluc <- ggplot(data = labs, aes(x = `Visit Type`, y = `Glucose (mg/dl)`, group = `Record ID`, color = as.factor(`Record ID`))) + 
  geom_line(show.legend = F) + guides(fill = "none") + stat_summary(aes(group = 1), geom = "point", fun.y = mean,
    shape = 17, size = 3, show.legend = F) + facet_wrap(~ Group)
p_bun <- ggplot(data = labs, aes(x = `Visit Type`, y = `BUN (mg/dl)`, group = `Record ID`, color = as.factor(`Record ID`))) + 
  geom_line(show.legend = F) + guides(fill = "none") + stat_summary(aes(group = 1), geom = "point", fun.y = mean,
    shape = 17, size = 3, show.legend = F) + facet_wrap(~ Group)
p_creat <- ggplot(data = labs, aes(x = `Visit Type`, y = `Serum creatinine (mg/dl)`, group = `Record ID`, color = as.factor(`Record ID`))) + 
  geom_line(show.legend = F) + guides(fill = "none") + stat_summary(aes(group = 1), geom = "point", fun.y = mean,
    shape = 17, size = 3, show.legend = F) + facet_wrap(~ Group)
p_calc <- ggplot(data = labs, aes(x = `Visit Type`, y = `Calcium (mg/dl)`, group = `Record ID`, color = as.factor(`Record ID`))) + 
  geom_line(show.legend = F) + guides(fill = "none") + stat_summary(aes(group = 1), geom = "point", fun.y = mean,
    shape = 17, size = 3, show.legend = F) + facet_wrap(~ Group)
p_bili <- ggplot(data = labs, aes(x = `Visit Type`, y = `Total Bilirubin (mg/dl)`, group = `Record ID`, color = as.factor(`Record ID`))) + 
  geom_line(show.legend = F) + guides(fill = "none") + stat_summary(aes(group = 1), geom = "point", fun.y = mean,
    shape = 17, size = 3, show.legend = F) + facet_wrap(~ Group)
p_alkphos <- ggplot(data = labs, aes(x = `Visit Type`, y = `Alk Phos (U/L)`, group = `Record ID`, color = as.factor(`Record ID`))) + 
  geom_line(show.legend = F) + guides(fill = "none") + stat_summary(aes(group = 1), geom = "point", fun.y = mean,
    shape = 17, size = 3, show.legend = F) + facet_wrap(~ Group)
p_alt <- ggplot(data = labs, aes(x = `Visit Type`, y = `ALT (U/L)`, group = `Record ID`, color = as.factor(`Record ID`))) + 
  geom_line(show.legend = F) + guides(fill = "none") + stat_summary(aes(group = 1), geom = "point", fun.y = mean,
    shape = 17, size = 3, show.legend = F) + facet_wrap(~ Group)
p_ast <- ggplot(data = labs, aes(x = `Visit Type`, y = `AST (U/L)`, group = `Record ID`, color = as.factor(`Record ID`))) + 
  geom_line(show.legend = F) + guides(fill = "none") + stat_summary(aes(group = 1), geom = "point", fun.y = mean,
    shape = 17, size = 3, show.legend = F) + facet_wrap(~ Group)
p_prot <- ggplot(data = labs, aes(x = `Visit Type`, y = `Total Protein, S (g/dl)`, group = `Record ID`, color = as.factor(`Record ID`))) + 
  geom_line(show.legend = F) + guides(fill = "none") + stat_summary(aes(group = 1), geom = "point", fun.y = mean,
    shape = 17, size = 3, show.legend = F) + facet_wrap(~ Group)
p_alb <- ggplot(data = labs, aes(x = `Visit Type`, y = `Albumin (g/dl)`, group = `Record ID`, color = as.factor(`Record ID`))) + 
  geom_line(show.legend = F) + guides(fill = "none") + stat_summary(aes(group = 1), geom = "point", fun.y = mean,
    shape = 17, size = 3, show.legend = F) + facet_wrap(~ Group)
p_eGFR <- ggplot(data = labs, aes(x = `Visit Type`, y = `eGFR`, group = `Record ID`, color = as.factor(`Record ID`))) + 
  geom_line(show.legend = F) + guides(fill = "none") + stat_summary(aes(group = 1), geom = "point", fun.y = mean,
    shape = 17, size = 3, show.legend = F) + facet_wrap(~ Group)
p_BMI <- ggplot(data = labs, aes(x = `Visit Type`, y = `BMI`, group = `Record ID`, color = as.factor(`Record ID`))) + 
  geom_line(show.legend = F) + guides(fill = "none") + stat_summary(aes(group = 1), geom = "point", fun.y = mean,
    shape = 17, size = 3, show.legend = F) + facet_wrap(~ Group)

# plots of CGM data
p_tbr <- ggplot(data = cgm_summary, aes(x = week_dose, y = TBRmean, group = `Record ID`, color = as.factor(`Record ID`))) + 
  geom_line(show.legend = F) + guides(fill = "none") + labs(y = "% Time Below Range", x = "Week/Dose") + stat_summary(aes(group = 1), geom = "point", fun.y = mean,
    shape = 17, size = 3, show.legend = F, color = "black") + facet_wrap(~ Group, scales = "free_x") + theme(axis.text.x = element_text(size = 7))
p_sh <- ggplot(data = cgm_summary, aes(x = week_dose, y = SHmean, group = `Record ID`, color = as.factor(`Record ID`))) + 
  geom_line(show.legend = F) + guides(fill = "none") + labs(y = "% Severe Hypoglycemia", x = "Week/Dose") + stat_summary(aes(group = 1), geom = "point", fun.y = mean,
    shape = 17, size = 3, show.legend = F, color = "black") + facet_wrap(~ Group, scales = "free_x") + theme(axis.text.x = element_text(size = 7))

```

# Labs

## HbA1c

```{r echo=FALSE}
p_a1c
```

## Sodium

```{r echo=FALSE}
p_sod
```

## Potassium

```{r echo=FALSE}
p_pot
```

## Chloride

```{r echo=FALSE}
p_chlor
```

## Bicarbonate

```{r echo=FALSE}
p_bicarb
```

## Glucose

```{r echo=FALSE}
p_gluc
```

## BUN

```{r echo=FALSE}
p_bun
```

## Serum creatinine

```{r echo=FALSE}
p_creat
```

## Calcium

```{r echo=FALSE}
p_calc
```

## Bilirubin

```{r echo=FALSE}
p_bili
```

## Alkaline Phosphatase

```{r echo=FALSE}
p_alkphos
```

## ALT

```{r echo=FALSE}
p_alt
```

## AST

```{r echo=FALSE}
p_ast
```

## Total protein

```{r echo=FALSE}
p_prot
```

## Albumin

```{r echo=FALSE}
p_alb
```

## eGFR

```{r echo=FALSE}
p_eGFR
```

## BMI

```{r echo=FALSE}
p_BMI
```

# CGM

## Percent of Time Below Range

```{r echo=FALSE}
p_tbr
```

## Percent of Time in Severe Hypoglycemia

```{r echo=FALSE}
p_sh
```


