---
title: "Powell analysis"
author: "Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
  number_sections: yes
theme: readable
toc: yes
toc_depth: 4
toc_float: yes
---
  
```{r setup, include=FALSE}
library(readxl)
library(car)
library(emmeans)
library(tableone)
```

```{r }
dat <- readxl::read_xlsx("H:/Neonatology/Powell/Analysis discrepancy/9MonthOldSkeletalMuscleLipidsForClaire_6.1.22.xlsx",
                         sheet=1)
dat$mod_group <- paste(dat$Group,dat$`Treatment (PBS/ADN)`)

# rename variables
dat$X1.2.di16.0DG <- dat$`1,2-di16:0DG`
dat$X1.2.16.0.18.0DG <- dat$`1,2-16:0/18:0DG`
dat$X1.2.16.0.18.1DG <- dat$`1,2-16:0/18:1DG`
dat$X1.2.16.0.20.1DG <- dat$`1,2-16:0/20:1DG`
dat$X1.2.16.0.20.2DG <- dat$`1,2-16:0/20:2DG`
dat$X1.2.14.0.16.1DG_l <- log(dat$`1,2-14:0/16:1DG`)
dat$X1.2.16.1.18.1DG_l <- log(dat$`1,2-16:1/18:1DG`)
dat$X1.2.18.0.18.1DG_l <- log(dat$`1,2-18:0/18:1DG`)
dat$X1.2.18.0.20.4DG_l <- log(dat$`1,2-18:0/20:4DG`)
dat$X1.2.16.0.18.2DG_l <- log(dat$`1,2-16:0/18:2DG`)
dat$sex <- dat$`Sex (M/F)`


mod <- function(var) {
  f = as.formula(paste0(var,"~ dat$mod_group*dat$sex"))
  mod <- lm(f, data=dat)
  print(Anova(mod))
  
  f_noint_adj <- as.formula(paste0(var,"~ dat$mod_group + dat$sex"))
  mod_noint_adj <- lm(f_noint_adj, data=dat)
  print(Anova(mod_noint_adj))
  print(emmeans(mod_noint_adj, ~mod_group))
  
  f_noadj <- as.formula(paste0(var,"~ dat$mod_group"))
  mod_noadj <- lm(f_noadj, dat)
  print(Anova(mod_noadj))
  print(emmeans(mod_noadj, ~mod_group))
}
```

```{r}
mod("X1.2.di16.0DG")
mod("X1.2.16.0.18.0DG")
mod("X1.2.16.0.18.1DG")
mod("X1.2.16.0.20.1DG")
mod("X1.2.16.0.20.2DG")
mod("X1.2.14.0.16.1DG_l")
mod("X1.2.16.1.18.1DG_l")
mod("X1.2.18.0.18.1DG_l")
mod("X1.2.18.0.20.4DG_l")
mod("X1.2.16.0.18.2DG_l")
```


