---
title: "TODAY plasma metabolomics baseline analyses - adjusted linear models"
author: "Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    number_sections: yes
    theme: readable
    toc: yes
    toc_depth: 3
    toc_float: yes
---

```{r setup, include=FALSE}
library(limma)
library(dplyr)
library(caret)
library(purrr)
library(multtest)
library(openxlsx)
library(tableone)
library(EnhancedVolcano)
library(knitr)
library(regmed)

knitr::opts_chunk$set(echo = FALSE,warning = FALSE)

knitr::opts_chunk$set(echo = FALSE)
if(Sys.info()["sysname"] == "Windows"){
  home_dir = "E:/Petter Bjornstad/TODAY subaward"
} else if (Sys.info()["sysname"] == "Linux"){
  home_dir = "~/UCD/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/TODAY subaward/"
} else if (Sys.info()["sysname"] == "Darwin"){
  home_dir = "/Volumes/som/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/TODAY subaward/"
}
knitr::opts_knit$set(root.dir = home_dir)
```

```{r, include=FALSE}
load("./Metabolomic data/plasma.Rdata")

# load comorbidity data
load("./Clinical data/comorb.Rdata")

# load baseline risk factors
load("./Clinical data/TODAY/baserisk.Rdata")

# read in eGFR
ADDCBL_TODAY2 <- read.csv("./Clinical data/TODAY2/ADDCBL.csv")
gfr <- ADDCBL_TODAY2 %>% select(releaseid,mvisit,eGFR_FAS)
gfr <- gfr %>% filter(!is.na(eGFR_FAS))
gfr <- gfr %>% filter(mvisit=="M12")

# take only the baseline samples
plasma$Date.Drawn <- as.Date(plasma$Date.Drawn,format = "%m/%d/%Y")
base <- plasma %>% arrange(releaseid,Date.Drawn) %>% group_by(releaseid) %>% filter(row_number()==1)
base <- base %>% arrange(Date.Drawn)

# merge in complication data
base <- merge(base, comorb, by="releaseid",all.x=T, all.y=F)

# merge in baseline risk factors
base <- merge(base, baserisk, by="releaseid",all.x=T, all.y=F)

# merge in eGFR
data <- merge(base,gfr,by="releaseid",all.x=T,all.y=F)

# for mediation analyses, need baseline A1c, baseline metabolomics, year 2 eGFR
# not perfect that A1c is at the same time as metabolomics, but we can argue it is a 3-mo cumulative measure

# only keep observations with nonmissing values of covariates
#data <- data %>% filter(!is.na(HbA1c) & !is.na(eGFR_FAS))

# identify columns corresponding to proteins
#is_seq <- function(.x) grepl("^seq\\.[0-9]{4}", .x) # regex for analytes
is_seq <- function(.x) grepl("uM", .x)
seq <- is_seq(names(data))

# convert to numeric
data[,seq] <- apply(data[,seq],2,as.numeric)

# center and scale X, M, Y
# actually I think the prefilter function does this step
for_mediation <- cbind(data[,seq], data$si_1_ins0, data$eGFR_FAS)
colnames(for_mediation) <- c(colnames(for_mediation[1:58]),"si_1_ins0","eGFR_FAS")
seq <- is_seq(names(for_mediation))
#for_mediation <-  as.data.frame(apply(for_mediation,2,scale))

```

```{r}
dat.filter <- regmed.prefilter(x=for_mediation$si_1_ins0, mediator=for_mediation[,seq], y=for_mediation$eGFR_FAS)
colnames(dat.filter$mediator)
# no filtering done so need to center and scale manually
for_mediation <-  as.data.frame(apply(for_mediation,2,scale))

# remove variables with more than 80% missing
miss <- for_mediation[,seq] %>% dplyr::select(where(~mean(is.na(.)) > 0.8))
for_mediation <- for_mediation %>% dplyr::select(-one_of(colnames(miss)))
seq <- is_seq(names(for_mediation))

# fit regmed for grid of lambda penalties
lambda.grid <- seq(from = 1, to = 0.01, by = -0.01)
x1 <- for_mediation$si_1_ins0
y1 <- for_mediation$eGFR_FAS
med <- for_mediation[seq]
fit.grid <- regmed.grid(x=x1, mediator=for_mediation[,seq], y=y1,
                        lambda.grid, frac.lasso = 0.5)
print(fit.grid)
plot.regmed.grid(fit.grid)

fit.best <- regmed.grid.bestfit(fit.grid)
summary(fit.best)

edges.med <- regmed.edges(fit.best, type = "mediators")
plot.regmed.edges(edges.med)

edges.any <- regmed.edges(fit.best, type = "any")
plot.regmed.edges(edges.any)

dat <- regmed.lavaan.dat(x=x1, mediator=for_mediation[seq], y=y1)
mod.best <- regmed.lavaan.model(edges.med, fit.best)
mod.any <- regmed.lavaan.model(edges.any, fit.best)

fit.lav.med <- lavaan:::sem(model = mod.best, data = dat)
summary.lavaan(fit.lav.med)

fit.lav.any <- lavaan:::sem(model = mod.any, data = dat)
summary.lavaan(fit.lav.any)

```

```{r}
# trying simulated dataset
data(medsim)

dat.filter <- regmed.prefilter(x[, 1], med, y[, 1], k = 10)
colnames(dat.filter$mediator)

lambda.grid <- seq(from = 0.4, to = 0.01, by = -0.05)

x1 <- dat.filter$x
y1 <- dat.filter$y
med <- dat.filter$mediator

fit.grid <- regmed.grid(x1, med, y1, lambda.grid, frac.lasso = 0.8)

print(fit.grid)

plot.regmed.grid(fit.grid)

fit.best <- regmed.grid.bestfit(fit.grid)
summary(fit.best)

edges.med <- regmed.edges(fit.best, type = "mediators")
plot.regmed.edges(edges.med)

edges.any <- regmed.edges(fit.best, type = "any")
plot.regmed.edges(edges.any)

dat <- regmed.lavaan.dat(x1, med, y1)

mod.best <- regmed.lavaan.model(edges.med, fit.best)

mod.any <- regmed.lavaan.model(edges.any, fit.best)

fit.lav.med <- lavaan:::sem(model = mod.best, data = dat)
summary.lavaan(fit.lav.med)

fit.lav.any <- lavaan:::sem(model = mod.any, data = dat)
summary.lavaan(fit.lav.any)

```

```{r}
# trying exactly the same code but with TODAY data
# need to update with data and var names
data(medsim)

dat.filter <- regmed.prefilter(x[, 1], med, y[, 1], k = 10)
colnames(dat.filter$mediator)

lambda.grid <- seq(from = 0.4, to = 0.01, by = -0.05)

x1 <- dat.filter$x
y1 <- dat.filter$y
med <- dat.filter$mediator

fit.grid <- regmed.grid(x1, med, y1, lambda.grid, frac.lasso = 0.8)

print(fit.grid)

plot.regmed.grid(fit.grid)

fit.best <- regmed.grid.bestfit(fit.grid)
summary(fit.best)

edges.med <- regmed.edges(fit.best, type = "mediators")
plot.regmed.edges(edges.med)

edges.any <- regmed.edges(fit.best, type = "any")
plot.regmed.edges(edges.any)

dat <- regmed.lavaan.dat(x1, med, y1)

mod.best <- regmed.lavaan.model(edges.med, fit.best)

mod.any <- regmed.lavaan.model(edges.any, fit.best)

fit.lav.med <- lavaan:::sem(model = mod.best, data = dat)
summary.lavaan(fit.lav.med)

fit.lav.any <- lavaan:::sem(model = mod.any, data = dat)
summary.lavaan(fit.lav.any)

```

# Results

## Descriptive statistics

```{r echo=FALSE, include=TRUE}
kable(t1)
```
